<?php
// $Id$

/**
 * Implementation of hook_feeds_plugins().
 */
function feeds_xpathparser_feeds_plugins() {
  $path = drupal_get_path('module', 'feeds_xpathparser');
  $info = array();

  $info['FeedsXPathParserHTML'] = array(
    'name'        => t('XPath HTML parser'),
    'description' => t('Parse HTML using XPath.'),
    'handler'     => array(
      'parent' => 'FeedsParser',
      'class'  => 'FeedsXPathParserHTML',
      'file'   => 'FeedsXPathParser.inc',
      'path'   => $path,
    ),
  );

   $info['FeedsXPathParserXML'] = array(
    'name'        => t('XPath XML parser'),
    'description' => t('Parse XML using XPath.'),
    'handler'     => array(
      'parent' => 'FeedsParser',
      'class'  => 'FeedsXPathParserXML',
      'file'   => 'FeedsXPathParser.inc',
      'path'   => $path,
    ),
  );

  return $info;
}

/**
 * Implements hook_form_feeds_ui_mapping_form_alter().
 *
 * This is an interesting bit of work. Each source name has to be unique,
 * but we have no idea how many to create with getMappingSources() because we
 * don't know how many targets there are going to be.
 *
 * The solution is to keep track in the form how many have been added.
 */
function feeds_xpathparser_form_feeds_ui_mapping_form_alter(&$form, &$form_state) {
  $newest_xpath_mapping = array();
  foreach ($form['#mappings'] as $mapping) {
    if (strpos($mapping['source'], 'xpathparser:') === 0) {
      $newest_xpath_mapping = $mapping;
    }
  }
  if (!empty($newest_xpath_mapping)) {
    list($a, $count) = explode(':', $newest_xpath_mapping['source']);
    $default_source = $a . ':' . '0';
    $label = $form['source']['#options'][$default_source];
    unset($form['source']['#options'][$default_source]);
    $form['source']['#options'][$a . ':' . ++$count] = $label;
  }
}
